[package]
name = "subway-rs"
version = "0.5.2"
edition = "2021"
license = "MIT"
description = "A Highly Optimized Sandwich Bot Built with Pure Rust and Huff"
authors = ["asnared <https://github.com/refcell>"]
repository = "https://github.com/refcell/subway-rs"
keywords = ["Rust", "Ethereum", "Arbitrage", "Sandwich"]

[dependencies]
# Errros
eyre = { version = "0.6" }
thiserror = "1.0.31"

# Core
tokio = { version = "1.0.1", features = ["full"] }
# ethers = { git = "https://github.com/gakonst/ethers-rs", features = [ "abigen", "ws", "rustls" ] }
ethers = { version = "0.17.0", features = [ "abigen", "ws", "rustls" ] }
ethers-flashbots = "0.10.0"

# Misc
hex = "0.4.3"
bytes = "1.2.1"
rlp = { version = "0.5.1", default-features = false }
rand = "0.8.5"
futures = "0.3.23"
reqwest = { version = "0.11.10", features = ["json", "blocking"] }

# Telemtry
yansi = "0.5.1"
ansi_term = "0.12.1"
tracing = "0.1.36"
tracing-bunyan-formatter = "0.3.4"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.16", features = ["fmt", "env-filter", "ansi"] }
chrono = "0.4.22"

# Serialization
serde = { version = "1.0.137", features = ["derive"] }
serde_json = { version = "1.0.82", features = [ "raw_value" ] }
dotenv = "0.15.0"

[dev-dependencies]
tracing-test = "0.2.3"
criterion = { version = "0.4", features = [ "async_tokio", "plotters" ]}
plotters = "0.3.3"


[lib]
name = "subway_rs"
path = "src/lib.rs"

[[bin]]
name = "subway"
path = "src/main.rs"

[[bench]]
name = "uniswap"
harness = false

[[bench]]
name = "utils"
harness = false

[[bench]]
name = "relayer"
harness = false
